env:
  num_observations: 48

terrain:
  mesh_type: 'trimesh'

control:
  control_type: 'P'
  stiffness: 10.0
  damping: 0.25
  action_scale: 0.25
  decimation: 4

asset:
  file: "{LEGGED_GYM_ROOT_DIR}/resources/robots/a1/urdf/a1.urdf"
  name: "go"
  self_collisions: 1 # 1 to disable, 0 to enable

rewards:
  soft_dof_pos_limit: 0.9
  base_height_target: 0.25
  scales:
    torques: -0.0002
    dof_pos_limits: -10.0
    base_height: -0.0

policy:
  actor_hidden_dims:  [128, 64, 32]
  critic_hidden_dims: [128, 64, 32]
  activation: 'elu' # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid

runner:
  max_iterations: 300